FROM postgres:latest

# Copia o script de inicialização para o container
COPY init-db.sh /docker-entrypoint-initdb.d/

# Define as variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432